server:
    port: 8080
spring:
    application:
        name: corona-killer-backend
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                show_sql: true
                format_sql: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ceng453_local
        username: yavuz
        password: p@ssw0rd

