server:
    port: 8080
spring:
    application:
        name: corona-killer-backend
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                show_sql: true
                format_sql: true
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://144.122.71.144:3306/database_group18
        username: user_group18
        password: zaD>mDT0nT"YIsAy

