server:
    port: 8080
spring:
    application:
        name: corona-killer-backend
#    jpa:
#        hibernate:
#            ddl-auto: create
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#                show_sql: true
#                format_sql: true
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/coronakiller?useSSL=false
#        username: yavuz
#        password: 123

